name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Check directory
      run: ls -la
    - name: Publish to deploy
      run:  dotnet publish SchVictorina.WebAPI/SchVictorina.WebAPI.csproj -p:PublishDir=publish -c Release
    - name: Set correct web.config
      run:  mv /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web_deploy.config /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web.config
    - name: Remove settings.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/settings.xml
    - name: Remove users.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/users.xml
    - name: FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        # FTP host
        ftp_host: ${{ secrets.FTP_SERVER }}
        # FTP username
        ftp_username: ${{ secrets.FTP_USERNAME }}
        # FTP password
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        # The local folder to copy
        local_source_dir: /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/
        # The remote folder
        dist_target_dir: bot
        # Delete files not present in the local folder on the remote folder
        delete: true
        # Download only newer files
        only_newer: false
        # Disable SSL certificate verification
        disable_ssl_certificate_verification: true
        # Optional raw string of flags for lftp eg. --no-empty-dirs
        other_flags: -p --no-perms
