name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Check directory
      run: ls -la
    - name: Publish to deploy
      run:  dotnet publish SchVictorina.WebAPI/SchVictorina.WebAPI.csproj -p:PublishDir=publish -c Release
    - name: Set correct web.config
      run:  mv /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web_deploy.config /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web.config
    - name: Remove settings.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/settings.xml
    - name: Remove users.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/users.xml
    - name: Upload program files and start application pool
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish"
        remoteDir: "bot"
    - name: Upload the lastest configs
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config"
        remoteDir: "bot/Config"
    - name: Upload the lastest images
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config"
        remoteDir: "bot/Images"
