name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Check directory
      run: ls -la
    - name: Publish to deploy
      run:  dotnet publish SchVictorina.WebAPI/SchVictorina.WebAPI.csproj -p:PublishDir=publish -c Release
    - name: Set correct web.config
      run:  mv /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web_deploy.config /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/web.config
    - name: Remove settings.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/settings.xml
    - name: Remove users.xml
      run: rm /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/Config/users.xml
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
       host: ${{ secrets.FTP_SERVER }}
       # FTP user
       user: ${{ secrets.FTP_USERNAME }}
    # FTP password
       password: ${{ secrets.FTP_PASSWORD }}
    # Force SSL encryption
       forceSsl: false
    # Local directory
       localDir: /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish/
    # Remote directory
       remoteDir: bot
        
