name: Deployment

on: [push, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check directory
      run: ls -la
    - name: Publish to deploy
      run:  dotnet publish SchVictorina.WebAPI/SchVictorina.WebAPI.csproj -p:PublishDir=publish -c Release
    - name: Change directory
      run: cd /home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/
    - name: Remove settings.xml
      run: rm settings.xml
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/home/runner/work/schvictorina/schvictorina/SchVictorina.WebAPI/publish"
        remoteDir: "bot"

