name: .NET

on:
   realise

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Test to deploy
      run: dotnet test --verbosity normal

    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "publish"
        remoteDir: "bot"

